source :rubygems

gem 'rails'

gem "jquery-rails"
gem 'sqlite3-ruby', :require => 'sqlite3'

group :test, :development do
  gem 'cucumber-rails'
  gem 'pickle'
  gem 'database_cleaner'
  gem "rails3-generators"
  gem "shoulda-matchers"
  gem "rspec-rails"
  gem "rcov"
  gem "ZenTest"
  gem "autotest-rails"
  gem "factory_girl_rails"
  gem "ruby-debug"
end
